version: "3"

services:
  appointments_db:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: appointment

    ports:
      - "3306:3306"

    volumes:
      - appointments_db:/var/lib/mysql

  appointments_service:
    build: ./appointments_service

    container_name: appointments_service_container

    command: ["python", "run.py"]

    restart: on-failure

    volumes:
      - ./appointments_service:/app/

    links:
      - appointments_db

    depends_on:
      - appointments_db

    environment:
      MYSQL_HOST: appointments_db
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: appointment

    ports:
      - "5001:5000"

volumes:
  appointments_db:
